### PR TITLE
Order search results by episode published date

### LINKED ISSUE #141: Episode sorting
Would like to be able to sort episodes (on search page) by release date.

### PR DESCRIPTION
**Pull request by Madsn**
Closes #141 

Sorts search results by release date.

### CODE REVIEW

**Comment by Madsn** [comment]
image

**Comment by Madsn** [comment]
Odd. "Works on my machine". Will have a look at the failing build.

**Comment by Madsn** [comment]
So I updated the search URL in cypress config and the tests run now - we have the search URL duplicated in the repo (introduced in PR #162). I'm not sure why these two urls not being in sync causes the test to not see any search results, but good thing it did since it made me realize I needed to update the URL in the cypress config file as well.

**Comment by davefollett** [comment]
@Madsn As part of the e2e (cypress) tests we intercept outbound calls based on the URL routes and then feedback in test data.  If the routes don't match, the calls will go out to the real server and return real results which do not line up with the test data.

I'll create an issue to make this more robust.

**Comment by MinimumViablePerson** [comment]
Looks good. So, do we want to wait until the tests are fixed before we push this?

**Pull request merged**
